---
- name: install nginx
  apt:
    pkg:
    - "nginx"
    state: present

- name: copy nginx.conf template
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: copy nginx site config template
  template:
    src: "nginx_default_site.conf.j2"
    dest: "/etc/nginx/sites-available/default_site"
    mode: 0644

- name: remove default site
  file:
    path: /etc/nginx/site-enabled/default
    state: absent

- name: activate site
  file:
    src: /etc/nginx/sites-available/default_site
    dest: /etc/nginx/sites-enabled/default_site
    owner: root
    group: root
    state: link

- name: check if certs in distribution package
  stat: path="{{ project_path }}/.lego/certificates/_.tu-berlin-streaming.de.crt"
  register: cert_stat

- name: ansible create directory with mode setting example
  file:
    path: /etc/livestreaming-certs
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: move crt
  command: mv {{ project_path }}/.lego/certificates/_.tu-berlin-streaming.de.crt /etc/livestreaming-certs
  when: cert_stat.stat.exists

- name: Change crt permissions
  file:
    path: /etc/livestreaming-certs/_.tu-berlin-streaming.de.crt
    owner: root
    group: root
    mode: '0644'
  when: cert_stat.stat.exists

- name: move key
  command: mv {{ project_path }}/.lego/certificates/_.tu-berlin-streaming.de.key /etc/livestreaming-certs
  when: cert_stat.stat.exists

- name: Change key permissions
  file:
    path: /etc/livestreaming-certs/_.tu-berlin-streaming.de.key
    owner: root
    group: root
    mode: '0600'
  when: cert_stat.stat.exists

- name: restart nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
