---
- name: copy nginx.conf template
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: copy nginx site config template
  template:
    src: "nginx_default_site.conf.j2"
    dest: "/etc/nginx/sites-available/default_site"
    mode: 0644

- name: remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: activate site
  file:
    src: /etc/nginx/sites-available/default_site
    dest: /etc/nginx/sites-enabled/default_site
    owner: root
    group: root
    state: link

- name: restart nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
