---
- name: create project path
  file:
    dest: "{{ project_path }}"
    mode: '755'
    state: directory
    owner: root
    group: root

- name: create server dir in project path
  file:
    dest: "{{ project_path }}/server"
    mode: '755'
    state: directory

- name: Extract videbo source files (copies tar file from local first)
  unarchive:
    src: "{{ local_deployment_tar_path }}"
    dest: "{{ project_path }}/server"

- name: copy config
  template:
    src: "config.ini.j2"
    dest: "{{ project_path }}/server/config.ini"
    mode: '640'
