---
- name: create videbo user
  user:
    name: videbo
    state: present

- name: give user project ownership
  file:
    path: "{{ project_path }}"
    owner: videbo
    group: videbo
    recurse: true

- name: give user video directory ownership
  file:
    path: "{{ lvm_video_path }}"
    owner: videbo
    group: videbo
    recurse: true

- name: create venv
  command:
    cmd: "python3 -m venv venv"
    creates: "{{ project_path }}/venv"
    chdir: "{{ project_path }}"
  become: true
  become_user: videbo

- name: install python dependencies
  command:
    cmd: "{{ project_path }}/venv/bin/pip install -r {{ project_path }}/server/requirements.txt"
  become: true
  become_user: videbo

- name: copy systemd unit
  template:
    src: "videbo-distributor-node.service.j2"
    dest: "/etc/systemd/system/videbo-distributor-node.service"
    mode: 0644

- name: start systemd unit
  systemd:
    state: started
    enabled: true
    name: videbo-distributor-node

