---
- name: create videbo group
  group:
    name: videbo
    state: present

- name: create videbo user
  user:
    name: videbo
    state: present
    system: yes
    group: videbo
    create_home: no

- name: create videbo_deploy user (manages code)
  user:
    name: videbo_deploy
    state: present
    system: yes
    group: videbo
    create_home: no

- name: give deploy user server dir ownership
  file:
    path: "{{ project_path }}/server"
    owner: videbo_deploy
    group: videbo
    recurse: true

- name: give user video directory ownership
  file:
    path: "{{ stored_videos_path }}"
    owner: videbo
    group: videbo
    recurse: true

- name: create venv path
  file:
    dest: "{{ project_path }}/venv"
    mode: '755'
    state: directory
    owner: videbo_deploy
    group: videbo

- name: create venv
  command:
    cmd: "su -c 'python3 -m venv .' videbo_deploy"
    creates: "{{ project_path }}/venv/bin/python"
    chdir: "{{ project_path }}/venv"

- name: install python dependencies
  command:
    cmd: "su -c '{{ project_path }}/venv/bin/pip install -r {{ project_path }}/server/requirements.txt' videbo_deploy"

- name: copy systemd unit
  template:
    src: "videbo-distributor.service.j2"
    dest: "/etc/systemd/system/videbo-distributor.service"
    mode: 0644

- name: start systemd unit
  systemd:
    state: restarted
    enabled: true
    name: videbo-distributor

- name: create directory for optional certbot webroot configuration
  file:
    dest: "{{ project_path }}/var/acme-challenge/"
    mode: '755'
    state: directory
    owner: root
    group: root
