---
- name: install nginx
  apt:
    pkg:
    - "nginx"
    state: present

- name: copy nginx.conf template
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    mode: 0644

- name: restart nginx service
  systemd:
    state: restarted
    daemon_reload: yes
    name: nginx
