---
- name: install gnupg2
  apt:
    pkg:
    - "gnupg2"
    state: present

- name: Add telegraf signing key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add telegraf repo
  apt_repository:
    repo: deb https://repos.influxdata.com/debian buster stable
    state: present

- name: install telegraf
  apt:
    pkg:
    - "telegraf"
    state: present
    update_cache: yes

- name: copy config template
  template:
    src: "telegraf.conf.j2"
    dest: "/etc/telegraf/telegraf.conf"
    mode: 0644

- name: restart telegraf service
  systemd:
    state: restarted
    daemon_reload: yes
    name: telegraf
