# This composite action is a simple workaround for failing fetches documented in this issue:
# https://github.com/federicocarboni/setup-ffmpeg/issues/19
#
# Inspired by this comment:
# https://github.com/federicocarboni/setup-ffmpeg/issues/19#issuecomment-2063798309

name: 'Tenacious FFmpeg setup'
description: 'Installs FFmpeg with a maximum of two retries, if setup fails for any reason'

runs:
  using: 'composite'
  steps:
    - name: Setup FFmpeg
      id: attempt-0
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Setup FFmpeg (first retry)
      if: ${{ steps.attempt-0.outcome == 'failure' }}
      id: attempt-1
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3

    - name: Setup FFmpeg (second retry)
      if: ${{ steps.attempt-1.outcome == 'failure' }}
      id: attempt-2
      continue-on-error: true
      uses: FedericoCarboni/setup-ffmpeg@v3
