name: CI - Tests & Checks

on:
  push:
    branches:
      - master

jobs:
  unit-tests:
    name: Unit tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements/dev.txt'

    - name: Upgrade pip
      run: pip install -U pip

    - name: Install dependencies
      run: pip install -Ur requirements/dev.txt

    - name: Install Videbo
      run: pip install -e .

    - name: Run unit tests for Python ${{ matrix.python-version }}
      if: ${{ matrix.python-version != '3.11' }}
      run: python -m tests

    - name: Run unit test coverage script for Python 3.11 and save total percentage
      if: ${{ matrix.python-version == '3.11' }}
      run: |
        total=$(./scripts/cov.sh)
        [[ $? -eq 0 ]] && echo "coverage=${total}" >> $GITHUB_ENV

    outputs:
      coverage: ${{ env.coverage }}

  e2e-tests:
    name: End-to-end tests (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements/dev.txt'

    - uses: FedericoCarboni/setup-ffmpeg@v1
      id: setup-ffmpeg

    - name: Upgrade pip
      run: pip install -U pip

    - name: Install dependencies
      run: pip install -Ur requirements/dev.txt

    - name: Install Videbo
      run: pip install -e .

    - name: Create temporary storage directory
      run: mkdir -p /tmp/videbo/storage

    - name: Run end-to-end tests for Python ${{ matrix.python-version }}
      run: python -m tests 'e2e_test*.py'

  type-checks:
    name: Type checks with mypy (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements/dev.txt'

    - name: Upgrade pip
      run: pip install -U pip

    - name: Install dependencies
      run: pip install -Ur requirements/dev.txt

    - name: Run mypy
      run: mypy

  lint:
    name: Lint with flake8 (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: 'requirements/dev.txt'

    - name: Upgrade pip
      run: pip install -U pip

    - name: Install flake8
      run: pip install -U flake8

    - name: Run flake8
      run: flake8 src/ tests/
